# SPDX-FileCopyrightText: 2022 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Woodpecker CI agent path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ woodpecker_ci_agent_uid }}"
    group: "{{ woodpecker_ci_agent_gid }}"
  with_items:
    - "{{ woodpecker_ci_agent_base_path }}"

- name: Ensure Woodpecker CI agent support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ woodpecker_ci_agent_base_path }}/{{ item }}"
    owner: "{{ woodpecker_ci_agent_uid }}"
    group: "{{ woodpecker_ci_agent_gid }}"
    mode: "0640"
  with_items:
    - env

- name: Ensure Woodpecker CI agent image is pulled
  community.docker.docker_image:
    name: "{{ woodpecker_ci_agent_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ woodpecker_ci_agent_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else woodpecker_ci_agent_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Woodpecker CI agent container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ woodpecker_ci_agent_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Woodpecker CI agent systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/woodpecker-ci-agent.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ woodpecker_ci_agent_identifier }}.service"
    mode: "0644"
