# SPDX-FileCopyrightText: 2022 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Woodpecker CI agent systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ woodpecker_ci_agent_identifier }}.service"
  register: woodpecker_ci_agent_service_stat

- name: Uninstall Woodpecker CI agent systemd services and files
  when: woodpecker_ci_agent_service_stat.stat.exists | bool
  block:
    - name: Ensure Woodpecker CI agent systemd service is stopped
      ansible.builtin.service:
        name: "{{ woodpecker_ci_agent_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Woodpecker CI agent systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ woodpecker_ci_agent_identifier }}.service"
        state: absent

    - name: Ensure Woodpecker CI agent container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ woodpecker_ci_agent_container_network }}"
        state: absent

    - name: Ensure Woodpecker CI agent container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ woodpecker_ci_agent_container_network }}
      register: network_deletion_result
      changed_when: woodpecker_ci_agent_container_network in network_deletion_result.stdout

    - name: Ensure Woodpecker CI agent path does not exist
      ansible.builtin.file:
        path: "{{ woodpecker_ci_agent_base_path }}"
        state: absent
